Fix "prettyPrint" crashing the Netconf readiness suite
There really is no need for prettyprinting in the Netconf
readiness suite as the only thing the suite is doing with the
data is checking that it is there (the request returned OK).

The "prettyPrint" argument of the URL started to make
problems recently:

  Keyword 'Check_Netconf_Connector' failed after retrying
  for minute. The last error was: TypeError: get() got an
  unexpected keyword argument 'restconf/config/network-\
  topology:network-topology/topology/topology-netconf/node/\
  controller-config/yang-ext:mount/config:modules/module/\
  odl-sal-netconf-connector-cfg:sal-netconf-connector/\
  controller-config/?prettyPrint'

Note the "?prettyPrint" at the end.

To counter this the "?prettyPrint=true" suffix was removed
from the URL used to check whether Netconf is working or not.
However to make sure it won't just slip away another test
case was added to try to run the prettyprinting when we are
sure Netconf is working so that we have something that
detects when the "?prettyPrint=true" argument breaks.

Change-Id: Ia23b6aa3baccfc21734ec78ba65abcb0e4bcb66f
Signed-off-by: Jozef Behran <jbehran@cisco.com>