Use Get_Request in netconf ready suite
When Get is used, it fails:
TypeError: get() got an unexpected keyword argument

Change-Id: I4d937c5d3c3aa6076ad06d333923ccbf30b27265
Signed-off-by: Vratko Polak <vrpolak@cisco.com>