Ignore pep8 E722
Existing code has started to fail on this error and causing
verify jobs to fail that have nothing to do with said existing
code. For now, we can ignore this to let work continue in
the int/test repo.

A jira ticket will be opened for someone to fix those related
erorrs (pasted below) and then remove this ignore = E722
statement

pep8 create: /w/workspace/integration-test-tox-verify-master/.tox/pep8
pep8 installdeps: flake8
pep8 installed: configparser==3.5.0,enum34==1.1.6,flake8==3.5.0,mccabe==0.6.1,pycodestyle==2.3.1,pyflakes==1.6.0
pep8 runtests: PYTHONHASHSEED='2589701320'
pep8 runtests: commands[0] | flake8
./csit/libraries/AAAJsonUtils.py:208:13: E722 do not use bare except'
            except:
            ^
./csit/libraries/AAAJsonUtils.py:285:13: E722 do not use bare except'
            except:
            ^
./csit/libraries/AAAJsonUtils.py:322:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:358:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:394:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:431:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:468:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:505:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:542:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:581:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:621:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:661:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:701:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:741:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/AAAJsonUtils.py:781:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/ClusterStateLibrary.py:48:17: E722 do not use bare except'
                except:
                ^
./csit/libraries/IoTDM/iotdm.py:96:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/IoTDM/iotdm.py:129:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/IoTDM/iotdm.py:137:5: E722 do not use bare except'
    except:
    ^
./csit/libraries/IoTDM/iotdm.py:145:5: E722 do not use bare except'
    except:
    ^
./csit/scripts/push_to_elk.py:142:1: E722 do not use bare except'
except:
^
./csit/scripts/push_to_elk.py:324:9: E722 do not use bare except'
        except:
        ^
./csit/scripts/push_to_elk.py:337:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/isolate.py:49:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/isolate.py:60:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/isolate.py:66:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/monitor.py:72:9: E722 do not use bare except'
        except:
        ^
./tools/clustering/cluster-monitor/monitor.py:110:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/monitor.py:119:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/monitor.py:134:5: E722 do not use bare except'
    except:
    ^
./tools/clustering/cluster-monitor/rejoin.py:46:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/rejoin.py:57:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/timed_isolation.py:51:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/timed_isolation.py:62:1: E722 do not use bare except'
except:
^
./tools/clustering/cluster-monitor/timed_isolation.py:69:1: E722 do not use bare except'
except:
^
./tools/odl-mdsal-clustering-tests/clustering-performance-test/inventory_crawler.py:136:21: E722 do not use bare except'
                    except:
                    ^
./tools/odl-mdsal-clustering-tests/clustering-performance-test/shard_perf_test.py:225:13: E722 do not use bare except'
            except:
            ^
./tools/robot_check/tidytool.py:45:5: E722 do not use bare except'
    except:
    ^
ERROR: InvocationError: '/w/workspace/integration-test-tox-verify-master/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed

Change-Id: Iee989ea6f2bcc3149988eb2e430fc7246c2d97e2
Signed-off-by: Jamo Luhrsen <jluhrsen@redhat.com>