Update patch set 1
Patch Set 1:

> org.jclouds.compute.callables.ScriptStillRunningException: time up waiting 300s 

This Change needs to be rebased manually by its Owner.

Patch-set: 1
Reviewer: Gerrit User 2046 <2046@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0