Netconf readiness: Do not put slash before question mark in URI
Also, use RequestsLibrary.Get_Request instead of RequestsLibrary.Get

This is to avoid this failure:
TypeError: get() got an unexpected keyword argument

Change-Id: I4d937c5d3c3aa6076ad06d333923ccbf30b27265
Signed-off-by: Vratko Polak <vrpolak@cisco.com>