resp.content->resp.text in Should Contain
The new python3 upgrade breaks our old checks for
Should Contain when using ${resp.content}. The
erorr is:

TypeError: a bytes-like object is required, not 'str'

There will probably be lots of places to fix this.

JIRA: INTTEST-105
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>
Change-Id: I14726cef95e2d2e7355d6974eacb4646566aa7a5