Update patch set 1
Patch Set 1:

> > (2 comments)
 > >
 > > Venkatrangan, thank for your comments. I'll update it per your
 > > comments, I don't know how to run job in sandbox to verify this
 > > commit, please tell me detailed steps, I'll verify it by sandbox
 > > before submitting it for your review.
 > 
 > https://wiki.opendaylight.org/view/How_to_run_jobs_in_sandbox

Venkat, thank you so much for your guide, but I followed this one https://docs.opendaylight.org/projects/releng-builder/en/latest/jenkins.html#id20 to try it this morning, I have gotten a token from https://jenkins.opendaylight.org/sandbox/user/yyang13/configure because I was sfc committer before, but I failed to get authentication when I ran jenkins-jobs --conf jenkins.ini update -j jjb/ netvirt-csit-1node-0cmb-1ctl-2cmp-openstack-queens-upstream-stateful-snat-conntrack-fluorine

File "/home/yangyi/.virtualenvs/jbb/lib/python2.7/site-packages/jenkins/__init__.py", line 594, in jenkins_request
    raise JenkinsException(msg)
jenkins.JenkinsException: Error in request. Possibly authentication failed [403]: Forbidden

jenkins-jobs --conf jenkins.ini test jjb/ netvirt-csit-1node-0cmb-1ctl-2cmp-openstack-queens-upstream-stateful-snat-conntrack-fluorine

local test is ok.

My question is how this job can use https://git.opendaylight.org/gerrit/#/c/80358/ to run the specified job, and how the specified job knows to use https://git.opendaylight.org/gerrit/#/c/80358/?

I have sent an email to 'helpdesk@opendaylight.org' for getting a new token for my new ID yangyi01, but I'm not odl committer as Inspur employee, I'm not sure if I can get a token from 'helpdesk@opendaylight.org'

Patch-set: 1
Label: Verified=0