Update patch set 6
Patch Set 6:

Hi Luis,
While doing Cherry pick to make the setup for sandbox , getting the following error message: 
mininet@mininet-vm:~/genius/test\> git fetch ssh://vidya.s@git.opendaylight.org:29418/integration/test refs/changes/55/40155/6 && git cherry-pick FETCH_HEAD
From ssh://git.opendaylight.org:29418/integration/test
 * branch            refs/changes/55/40155/6 -> FETCH_HEAD
error: 'cherry-pick' is not possible because you have unmerged files.
hint: Fix them up in the work tree,
hint: and then use 'git add/rm <file>' as
hint: appropriate to mark resolution and make a commit,
hint: or use 'git commit -a'.
fatal: cherry-pick failed
mininet@mininet-vm:~/genius/test\>

Looks like to run in sandbox, code should first merge in jenkins, then need to do the cherry pick for running in sandbox. 
please let me know, how to proceed further

Patch-set: 6