Bump pre-commit black black to 22.8.0
Current version of black is not compatible with click 8.1.x:

  ImportError: cannot import name '_unicodefun' from 'click'

This issue has been fixed since 22.3.0:

https://github.com/psf/black/releases/tag/22.3.0

Upgrade black to the latest version (22.8.0).

Change-Id: Iacf8328ea4b7622412948238c206c5af4ff692cd
Signed-off-by: Sangwook Ha <sangwook.ha@verizon.com>