Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> Can you point to some logs indicating this failure?

copy-logs: netvirt-csit-hwvtep-3node-0cmb-1ctl-2cmp-openstack-rocky-upstream-stateful-silicon/96

neutron CLI is deprecated and will be removed in the future. Use openstack CLI instead.
DEBUG: stevedore.extension found extension EntryPoint(name='admin_token', value='keystoneauth1.loading._plugins.admin_token:AdminToken', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='none', value='keystoneauth1.loading._plugins.noauth:NoAuth', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='password', value='keystoneauth1.loading._plugins.identity.generic:Password', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='token', value='keystoneauth1.loading._plugins.identity.generic:Token', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v2password', value='keystoneauth1.loading._plugins.identity.v2:Password', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v2token', value='keystoneauth1.loading._plugins.identity.v2:Token', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3adfspassword', value='keystoneauth1.extras._saml2._loading:ADFSPassword', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3applicationcredential', value='keystoneauth1.loading._plugins.identity.v3:ApplicationCredential', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3fedkerb', value='keystoneauth1.extras.kerberos._loading:MappedKerberos', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3kerberos', value='keystoneauth1.extras.kerberos._loading:Kerberos', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3multifactor', value='keystoneauth1.loading._plugins.identity.v3:MultiFactor', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3oauth1', value='keystoneauth1.extras.oauth1._loading:V3OAuth1', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3oidcaccesstoken', value='keystoneauth1.loading._plugins.identity.v3:OpenIDConnectAccessToken', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3oidcauthcode', value='keystoneauth1.loading._plugins.identity.v3:OpenIDConnectAuthorizationCode', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3oidcclientcredentials', value='keystoneauth1.loading._plugins.identity.v3:OpenIDConnectClientCredentials', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3oidcpassword', value='keystoneauth1.loading._plugins.identity.v3:OpenIDConnectPassword', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3password', value='keystoneauth1.loading._plugins.identity.v3:Password', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3samlpassword', value='keystoneauth1.extras._saml2._loading:Saml2Password', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3token', value='keystoneauth1.loading._plugins.identity.v3:Token', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3tokenlessauth', value='keystoneauth1.loading._plugins.identity.v3:TokenlessAuth', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='v3totp', value='keystoneauth1.loading._plugins.identity.v3:TOTP', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='noauth', value='cinderclient.contrib.noauth:CinderNoAuthLoader', group='keystoneauth1.plugin')
DEBUG: stevedore.extension found extension EntryPoint(name='token_endpoint', value='openstackclient.api.auth_plugin:TokenEndpoint', group='keystoneauth1.plugin')
ERROR: neutronclient.shell float() argument must be a string or a number, not 'dict'
Traceback (most recent call last):
  File "/tmp/v/robot/lib64/python3.6/site-packages/neutronclient/shell.py", line 506, in run
    self.initialize_app(remainder)
  File "/tmp/v/robot/lib64/python3.6/site-packages/neutronclient/shell.py", line 608, in initialize_app
    self.authenticate_user()
  File "/tmp/v/robot/lib64/python3.6/site-packages/neutronclient/shell.py", line 581, in authenticate_user
    api_version=cloud_config.get_api_version('network'),
  File "/tmp/v/robot/lib64/python3.6/site-packages/openstack/config/cloud_region.py", line 447, in get_api_version
    float(version)
TypeError: float() argument must be a string or a number, not 'dict'
float() argument must be a string or a number, not 'dict'

Patch-set: 2