Update patch set 12
Patch Set 12:

> > I do not know if this suite ever worked but it seems like too
 > much
 > > lost effort if it really never did.
 > 
 > I would be surprised if it never worked.  it would be a shame to
 > let
 > a CSIT suite for a core project go away.
 > 
 > Ryan, I'm looking at the most recent verify job for this patch:
 > https://jenkins.opendaylight.org/releng/job/aaa-csit-verify-1node-idmlite/17/robot/report/log.html
 > 
 > what is wrong with the user create:
 > 
 > POST to: auth/v1/users
 > data is: {"enabled": "true", "description": "User-of-the-Force",
 > "name": "Leia-2016-01-30-20-14"}
 > 
 > the response is 400
 > 
 > actually, karaf.log helps:
 > error: domain is required to create the user account.  Please
 > provide a domain in your payload. details:  status: 400
 > 
 > 
 > what's the format for adding the domain info in the user create.
 > 
 > I'll see if I can help breathe life in to this.

Jamo,

This patch is certainly a step in the right direction.  What I did to make "Test Post New User" pass is use this payload:

{"description":"sample user description", "name":"${testusername}", "userid":"newuser@sdn", "domainid":"sdn", "email":""}

Then, I had to modify the AAAJsonUtils.py in order to correctly parse the result, since it expects it in a certain format, and that is not how AAA returns it.

Patch-set: 12